server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB

app:
  path:
    files: /home/marcus/pessoal/workspace/Synchronize/src/sharedfiles/
    filesSents: /home/marcus/pessoal/workspace/Synchronize/src/sharedFilesSents/